strong_complaint_patterns:
  - "\\bне могу\\b"
  - "\\bне получается\\b"
  - "\\bне работает\\b"
  - "\\bсписали\\b"
  - "\\bверните\\b"
  - "\\bвозврат\\b"
  - "\\bпропали деньги\\b"
  - "\\bжалоб(а|у|ы)\\b"
  - "\\bпретензи(я|ю|и)\\b"
  - "\\bв суд\\b"
  - "\\bв цб\\b"
  - "\\bужасно\\b"
  - "\\bобман\\b"
  - "\\bмошенничеств(о|а)\\b"
non_complaint_patterns:
  - "\\bспасибо\\b"
  - "\\bподскажите(,| )?как\\b"
  - "\\bвопрос\\b"
  - "\\bуточните\\b"
  - "\\bздравствуйте\\b"
